code optimizations
flipkart-incubator/batchman pull request #136
Opened 2017-03-04 12:39 UTC by guptasourabh

Changes -:
Initialising variable only when needed.
Corrected retry exponential logic so in present case if it fails then it again try with the same timeout rather than the exponential one , so in present case it will be like if 3 time retry happening then retry time is 1,2,4 rather than 2,4,8 , as first failure anyhow has timeout default of 1.
If array is getting initialize then initialize with correct size.

2017-03-04 13:25 UTC, guptasourabh commented
@anirudhramanan @kushalsharma @yasirmhd to review

2017-03-06 08:24 UTC, yasirmhd requested changes

2017-03-06 08:24 UTC, yasirmhd commented on batching/src/main/java/com/flipkart/batching/listener/NetworkPersistedBatchReadyListener.java
>      void registerReceiverIfRequired() {
Do we need the receiverRegistered any more? It should be based on the nullability of networkBroadcastReceiver

2017-03-06 09:38 UTC, yasirmhd approved these changes

2017-03-06 09:38 UTC, merged